services:
  web:
    image: django-app:latest
    container_name: django_web
    env_file:
      - /Users/changhy2001/Desktop/login/.env

  frontend:
    image: vue-app:latest
    container_name: vue_frontend

  nginx:
    image: nginx:alpine
    container_name: django_nginx
    ports:
      - "80:80"
    volumes:
      - /Users/changhy2001/Desktop/login/frontend/dist:/usr/share/nginx/html:ro
      - /Users/changhy2001/Desktop/login/backend/config/nginx:/etc/nginx/conf.d:ro
    depends_on:
      - web
      - frontend
