services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_web
    env_file:
      - .env
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_app
    volumes:
      - vue-dist:/app/dist
    command: ["echo", "Vue build complete"]

  nginx:
    image: nginx:alpine
    container_name: django_nginx
    ports:
      - "80:80"
    volumes:
      - ./backend/config/nginx:/etc/nginx/conf.d:ro
      - vue-dist:/usr/share/nginx/html:ro
    depends_on:
      - web
      - frontend

volumes:
  vue-dist:
