services:
  web:
    image: django-app:latest
    container_name: django_web
    command: daphne myproject.asgi:application --bind 0.0.0.0 --port 8000
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - static_volume:/app/myproject/staticfiles
      - media_volume:/app/media
    depends_on:
      - db

  frontend:
    image: vue-app:latest
    container_name: vue_frontend
    expose:
      - "80"    # Exposes port 80 internally only
    # No ports mapping here because Nginx will be the public entry point

  nginx:
    image: nginx:alpine
    container_name: django_nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./backend/config/nginx:/etc/nginx/conf.d:ro
    depends_on:
      - web
      - frontend

  db:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  static_volume:
  media_volume:
  postgres_data: