services:
  web:
    build: .
    container_name: django_web
    volumes:
      - ./static_volume:/app/myproject/staticfiles
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: django_nginx
    ports:
      - "8000:80"
    volumes:
      - ./static_volume:/app/myproject/staticfiles
      - ./myproject/config/nginx/myproject.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  static_volume:
