services:
  web:
    image: django-app:latest
    container_name: django_web
    env_file:
      - /Users/changhy2001/Desktop/orchestrator/.env

  nginx:
    image: nginx:alpine
    container_name: django_nginx
    ports:
      - "80:80"
    volumes:
      - /Users/changhy2001/Desktop/orchestrator/frontend/dist:/usr/share/nginx/html:ro
      - /Users/changhy2001/Desktop/orchestrator/backend/config/nginx:/etc/nginx/conf.d:ro
    depends_on:
      - web